# From the directory above docs:
# (run the copy-images script first)
# dactyl_build -t all -c docs/ExportDocs/dactyl-config-onboarding.yml --pdf
#--leave_temp_files
content_path: .
content_static_path: ./images
temporary_files_path: .
template_path: ./docs/ExportDocs/pdf_templates
template_static_path: ./docs/ExportDocs/pdf_templates/template_assets
default_template: template-l1p_pdf_content.html
default_pdf_template: template-l1p_pdf_content.html

filter_paths:
    - ./docs/ExportDocs/pdf_templates/filters

default_filters:
    - out_of_date
    - link_replacement
    - demote_headers
    - wikilinks

cover_page:
    display_name: "Index"
    pdf_template: template-l1p_pdf_cover.html
    html: index.html

targets:
    -   name: all
        display_name: Mojaloop Developer Onboarding
        image_re_subs:
            "[./\\w]*/([\\w%.-]+[.](jpg|JPG|png|PNG))": "images/\\1"
        image_subs:
            https://github.com/mojaloop/docs/blob/master/Wiki/Test%20Pyramid.png: images/Test%20Pyramid.png
            https://github.com/mojaloop/docs/blob/master/Wiki/Microservice%20testing.png: images/Microservice%20testing.png
            https://github.com/mojaloop/docs/blob/master/Wiki/PuttyConnection.png: images/PuttyConnection.png
            https://github.com/mojaloop/docs/blob/master/Wiki/PuttyConfig.png: images/PuttyConfig.png
            https://github.com/mojaloop/docs/blob/master/Wiki/Tracking%20requirements%20to%20results.png: images/Tracking%20requirements%20to%20results.png
            https://github.com/Mojaloop/docs/blob/master/Wiki/Glory%20of%20Rest.png: images/Glory%20of%20Rest.png
            https://github.com/mojaloop/docs/blob/master/Wiki/mergebtn.png: images/mergebtn.png
            https://github.com/mojaloop/docs/blob/master/Wiki/CreateBranch.png: images/CreateBranch.png
            https://github.com/mojaloop/docs/blob/master/Wiki/CompareNPull.png: images/CompareNPull.png
            https://github.com/mojaloop/docs/blob/master/Wiki/ConfirmNSquash.png: images/ConfirmNSquash.png
        link_subs:
            ./LevelOneClient/scenarios/Send%20Payment.md: SendPayment.html
            ./LevelOneClient: LevelOneClient.html
            ./DFSP/PendingTransactions/README.md: Invoices.html
            ./DFSP/BulkPayment/README.md: BulkPayments.html
            ../../DFSP#default-ports: DFSP.html#default-ports
            ./DFSP: DFSP.html
            ./ILP/ledger-adapter.md: ledger-adapter.html
            ./ILP: ILP.html
            ../CentralDirectory/central_directory_endpoints.md: CentralDirectory.html
            ./CentralDirectory: CentralDirectory.html
            ./CentralLedger: central_ledger.html
            ./CentralRules: central_rules.html
            ./JMeter: IntegrationTests.html
            ./ansible.yml: https://github.com/LevelOneProject/docs/blob/master/ILP/ansible.yml
            ./ledger-adapter.md: ledger-adapter.html
            ../Ports.md: ports.html
       # link_re_subs:
       #     "\\[\\[([\\w]*)\\]\\]": "./\\1.html"

   
pages:
# overview
    -   name: 'Contribution Guide'
        html: Contributionguide.html
        category: Onboarding
        md: mojaloop/contribute.md
        section_header: true
        targets:
            - all

# documentation
    -   name: 'Structure of the Documentation'
        html: Structure-of-the-Documentation.html
        category: 'Structure of the Documentation'
        md: mojaloop/contribute/Structure-of-the-Documentation.md
        section_header: true
        targets:
            - all

    -   name: 'Documentation and Template Standards'
        html: Documentation-and-Template-Standards.html
        category: 'Structure of the Documentation'
        md: mojaloop/contribute/Documentation-and-Template-Standards.md
        targets:
            - all

    -   name: 'Architecture Documentation Guidelines'
        html: Architecture-Documentation-Guidelines.html
        category: 'Structure of the Documentation'
        md: mojaloop/contribute/Architecture-Documentation-Guidelines.md
        targets:
            - all

 #   -   name: 'Documentation Style Guide'
 #       html: Documentation-Style-Guide.html
 #       category: 'Structure of the Documentation'
 #       md: mojaloop/contribute/Documentation-Style-Guide.md
 #       targets:
 #           - all

    -   name: 'README Template'
        html: README-Template.html
        category: 'Structure of the Documentation'
        md: mojaloop/contribute/README-Template.md
        targets:
            - all

# local test environment
    -   name: 'Creating a local test environment'
        html: devops.html
        category: Local Test Envirnment
        md: interop-devops/README.md
        section_header: true
        targets:
            - all

#Testing
    -   name: 'Testing strategy'
        html: Testing-strategy.html
        category: Testing
        md: mojaloop/contribute/Testing-strategy.md
        section_header: true
        targets:
            - all

    -   name: 'Use Case Tests'
        html: UseCaseTests.html
        category: Testing
        md: docs/test/README.md
        targets:
            - all

    -   name: 'Account Management Tests'
        html: AccountManagementTests.html
        category: Testing
        md: 'docs/test/account management tests.md'
        targets:
            - all

    -   name: 'Customer Management Tests'
        html: CustomerManagementTests.html
        category: Testing
        md: 'docs/test/customer management tests.md'
        targets:
            - all

    -   name: 'DFSP Management Tests'
        html: DFSPManagementTests.html
        category: Testing
        md: 'docs/test/dfsp management tests.md'
        targets:
            - all

    -   name: 'Fees Tests'
        html: FeesTests.html
        category: Testing
        md: 'docs/test/fees tests.md'
        targets:
            - all

    -   name: 'Pending Transaction Tests'
        html: PendingTransactionTests.html
        category: Testing
        md: 'docs/test/pending transaction tests.md'
        targets:
            - all

    -   name: 'Send Money Tests'
        html: SendMoneyTests.html
        category: Testing
        md: 'docs/test/send money tests.md'
        targets:
            - all

    -   name: 'Scenario Automation'
        html: scenarioAutomation.html
        category: Testing
        md: docs/test/end-to-end/readme.md
        targets:
            - all

    -   name: 'Integration Automation'
        html: IntegrationAutomation.html
        category: Testing
        md: docs/test/ilp-integration/README.md
        targets:
            - all


    -   name: 'Resilience Modeling and Anaylysis'
        html: RMA.html
        category: Appendix
        md: docs/test/rma.md
        targets:
            - all

# Writing code
    -   name: Setting up the development environment'
        html: development.html
        category: Writing code
        md: docs/DFSP/development.md
        targets:
            - all   

    -   name: 'Writing Code'
        html: Writing-Code.html
        category: Writing code
        md: mojaloop/contribute/Writing-Code.md
        targets:
            - all    

    -   name: 'Pragmatic REST Guidelines'
        html: Pragmatic-REST-Guidelines.html
        category: Writing code
        md: mojaloop/contribute/Pragmatic-REST-Guidelines.md
        targets:
            - all

    -   name: 'Branching Strategy'
        html: Branching-Strategy.html
        category: Writing code
        md: mojaloop/contribute/Branching-Strategy.md
        targets:
            - all


    -   name: 'Build and Publish NodeJS'
        html: Build-and-Publish-NodeJS.html
        category: Writing code
        md: mojaloop/contribute/Build-and-Publish-NodeJS.md
        targets:
            - all

    -   name: 'Code Quality Metrics'
        html: Code-Quality-Metrics.html
        category: Writing code
        md: mojaloop/contribute/Code-Quality-Metrics.md
        targets:
            - all

    -   name: 'Code  Style Guidelines'
        html: Code-Style.html
        category: Writing code
        md: mojaloop/contribute/Code-Style.md
        targets:
            - all

    -   name: 'GitHub Labels'
        html: GitHub-Labels.html
        category: Software Development Process
        md: mojaloop/contribute/GitHub-Labels.md
        targets:
            - all     
     
# Debugging
    -   name: 'Logging Standards'
        html: elk.html
        category: Debugging
        md: docs/Interop Services and Mule/logging-guidelines.md
        section_header: true
        targets:
            - all

    -   name: 'Kibana user guide'
        html: kibana-user-guide.html
        category: Infrastructure
        md: docs/ELK/kibana-user-guide.md
        targets:
            - all

# -------------------- Appendix ------------------------
    -   name: 'Terminology'
        html: terminology.html
        category: Appendix
        md: docs/terminology.md
        section_header: true
        targets:
            - all

    -   name: 'Design Decisions'
        html: Design-Decisions.html
        category: Appendix
        md: mojaloop/contribute/Decision-Items.md
        targets:
            - all

    -   name: 'Tools and Process Decisions'
        html: Tools-Decisions.html
        category: Appendix
        md: docs/decisions.md
        targets:
            - all

    -   name: 'FAQ'
        html: FAQ.html
        category: Appendix
        md: mojaloop/FAQ.md
        targets:
            - all

    -   name: 'User Story Workflow'
        html: user-story-workflow.html
        category: Appendix
        md: mojaloop/contribute/Pipeline.md
        targets:
            - all

    -   name: 'Roadmap'
        html: Roadmap.html
        category: Appendix
        md: mojaloop/contribute/Roadmap.md
        targets:
            - all      

# -------------------- Style Checker Rules ------------------------
#word_substitutions_file: plainlanguage_words.yaml
#phrase_substitutions_file: plainlanguage_phrases.yaml
